### ISSUE TITLE
Distribution

### ISSUE THREAD

**Issue by martincarapia** [AnthisCareerAcademy/EasyPunchCard#48]
We need to create an executable for distribution of the software to be streamlined. I've done research and this seems to work best for me

https://chatgpt.com/share/674384c9-14cc-8005-bac6-7367bb7354e6

**Comment by AungA07** [comment]
Where would I keep the exe file in the actual github repo

**Comment by martincarapia** [comment]
If you run pyinstaller on a windows machine it should make a windows executable. Since I ran it on MacOS it created a Unix Executable FIle. I used create-dmg tool to package it and make it all pretty for macOS.

**Comment by AungA07** [comment]
since the program is going to be ran on windows I'll keep it as an .exe
